### ISSUE TITLE
download_weights.py fails on CPU-only machine

### ISSUE THREAD

**Issue by dav0dea** [Lornatang/GAN-PyTorch#1]
When running download_weights.py on a CPU-only machine I get the error `RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.` in this line https://github.com/Lornatang/GAN-PyTorch/blob/782a31ecff985a6f295a8fb84939bc179b2c1843/gan_pytorch/models.py#L124

Should be an easy fix by passing the `map_location` argument to `load_state_dict_from_url`.

**Comment by Lornatang** [comment]
@PhilippThoelke Thank you. The machine I was running was on a machine with GPU. I will modify it as soon as possible.

**Comment by dav0dea** [comment]
I opened a pull request with a fix for that, feel free to have a look: https://github.com/Lornatang/GAN-PyTorch/pull/2
