### ISSUE TITLE
g-mnist pretrained is not found

### ISSUE THREAD

**Issue by pythonian23** [Lornatang/GAN-PyTorch#4]
```
generator = Generator.from_pretrained("g-mnist")
```
gives
```
HTTPError: HTTP Error 404: Not Found
```

It's attempting to download `https://github.com/Lornatang/GAN-PyTorch/releases/download/1.0/g-mnist-a0922495.pth`, which doesn't exist

**Comment by Lornatang** [comment]
See https://github.com/Lornatang/GAN-PyTorch/releases
